### PR TITLE
Fix/issue 325361846/"no module name board" / adjust for Python 3.x

### PR DESCRIPTION
**Pull request by lade043**
Changed the code, so it runs under Python 3. For this there have been multiple changes:

- `xrange` replaced by `range`
- imports changed for files of lib from `x` to `lib.x`
- created directory `data` in `sensehatsnake/lib/`

### CODE REVIEW

**Comment by lade043** [comment]
Closed pull request accidentaly

**Review by bradcornford — APPROVED** [review]

**Comment by bradcornford** [comment]
I'm not sure why you're moving the data directory, as it doesn't really live with libraries, and is still coded to write the the original directory.

**Comment by lade043** [comment]
Sorry my bad, I don't know why I've did it, but I can make a fix today or tomorrow. Should I do a new pull request?

**Comment by bradcornford** [comment]
Nah your okay, ill get that removed now. Thanks for your work!

**Pull request merged**
